name: ising-model-js
channels:
- defaults
- conda-forge
dependencies:
- anaconda=4.4.0=np112py36_0
- autopep8=1.3.2=py36_0
- certifi=2017.7.27.1=py36_0
- flake8=3.3.0=py36_0
- lockfile=0.12.2=py36_0
- markdown=2.6.9
- pandoc=1.19.2-0
- pelican=3.7.0
- pydocstyle=2.0.0=py36_0
- python-daemon=2.1.2=py36_0
- pylama=7.4.3=py_0
- rpy2=2.8.6=py36r3.4.1_2
- ruamel.yaml=0.15.34=py36_0
- tabulate=0.7.7
- typogrify=2.0.7
- r-essentials=1.6.0=r3.4.1_0
- r-commonmark=1.2=r3.4.1_0
- r-devtools=1.13.2=r3.4.1_0
- r-bookdown=0.4=r3.4.1_0
- r-lintr=1.0.0=r3.4.1_0

